services:
  # ==========================================
  # BROKER DE MENSAJERÍA (EDA)
  # ==========================================
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fica_rabbitmq
    ports:
      - "5672:5672"   # Puerto de conexión AMQP
      - "15672:15672" # Interfaz de administración web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - fica_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # BASE DE DATOS UNIFICADA: POSTGRESQL (RELACIONAL)
  # ==========================================
  postgres-shared:
    image: postgres:15-alpine
    container_name: fica_postgres_shared
    ports:
      - "5432:5432" # Un solo puerto para todas las DBs relacionales
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # 👇 Aquí declaramos todas las bases de datos lógicas de tus microservicios
      POSTGRES_MULTIPLE_DATABASES: fica_judge_iam,fica_judge_submissions,fica_judge_assignments
    volumes:
      - postgres_shared_data:/var/lib/postgresql/data
      # El script que crea las 3 bases de datos automáticamente
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - fica_network

  # ==========================================
  # BASE DE DATOS UNIFICADA: MONGODB (DOCUMENTAL)
  # ==========================================
  mongo-shared:
    image: mongo:6
    container_name: fica_mongo_shared
    ports:
      - "27017:27017" # Un solo puerto para todas las colecciones NoSQL
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_secret
    volumes:
      - mongo_shared_data:/data/db
    networks:
      - fica_network

  # ==========================================
  # CACHÉ Y SESIONES (MEMORIA VOLÁTIL)
  # ==========================================
  session-db:
    image: redis:7-alpine
    container_name: fica_session_db
    ports:
      - "6379:6379"
    networks:
      - fica_network

volumes:
  postgres_shared_data:
  mongo_shared_data:

networks:
  fica_network:
    driver: bridge