# ==========================================
# 1. ETAPA DE CONSTRUCCIÓN (BUILDER)
# ==========================================
FROM node:18-alpine AS builder

WORKDIR /usr/src/app

# Copiamos los archivos de configuración de la raíz
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

# Instalamos TODAS las dependencias
RUN npm install

# Copiamos SOLO el código del microservicio de catálogo
COPY apps/problem-catalog-service apps/problem-catalog-service/

# Compilamos el microservicio de catálogo
RUN npm run build problem-catalog-service

# ==========================================
# 2. ETAPA DE PRODUCCIÓN (RUNNER)
# ==========================================
FROM node:18-alpine

WORKDIR /usr/src/app

# Copiamos solo el package.json
COPY package*.json ./

# Instalamos SOLO dependencias de producción
RUN npm install --only=production

# Traemos el código compilado desde la etapa anterior
COPY --from=builder /usr/src/app/dist/apps/problem-catalog-service ./dist

# Variables de entorno
ENV NODE_ENV=production
ENV CATALOG_PORT=3002

# Exponemos el puerto
EXPOSE 3002

# Ejecutamos el servicio
CMD ["node", "dist/main"]