# Etapa 1: Construcción
FROM node:20-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install # <-- CAMBIO AQUÍ

COPY . .
RUN npm run build iam-service

# Etapa 2: Producción
FROM node:20-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --omit=dev # <-- CAMBIO AQUÍ

COPY --from=builder /usr/src/app/dist ./dist
EXPOSE 3001
CMD ["node", "dist/apps/iam-service/main"]